/* ==========================================================================
   NCSmall.Farm V.2 — Demo Parcels Data
   ========================================================================== */

window.DEMO_PARCELS = [
  {
    id: 'parcel-001',
    owner: 'Johnson, James',
    address: '1234 Old Farm Rd, Greensboro, NC',
    lat: 36.210, lon: -79.701,
    acreage: 23,
    soilType: 'Cecil sandy loam (CeB2)',
    soilDrainage: 'Well drained',
    slopePct: '4-8%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '400ft - Reedy Fork Creek',
    concerns: ['Soil erosion on south slope', 'No riparian buffer', 'Nutrient runoff risk'],
    practices: [
      {code: '340', name: 'Cover Crop', priority: 'high'},
      {code: '391', name: 'Riparian Forest Buffer', priority: 'high'}
    ],
    eqipEstimate: '$4,200 - $8,500',
    priorityScore: 87,
    priorityLevel: 'high',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Cropland / Row crops',
    pvuStatus: true,
    vadEnrolled: 'VAD',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-002',
    owner: 'Smith, Sarah',
    address: '8900 Huffine Mill Rd, Gibsonville, NC',
    lat: 36.098, lon: -79.545,
    acreage: 45,
    soilType: 'Appling sandy loam (ApB)',
    soilDrainage: 'Well drained',
    slopePct: '2-6%',
    floodZone: 'Zone AE (1% annual chance)',
    wetlands: true,
    streamProximity: '150ft - Buffalo Creek',
    concerns: ['Seasonal flooding', 'Compaction in lower fields'],
    practices: [
      {code: '328', name: 'Conservation Crop Rotation', priority: 'medium'},
      {code: '590', name: 'Nutrient Management', priority: 'high'}
    ],
    eqipEstimate: '$6,000 - $12,000',
    priorityScore: 72,
    priorityLevel: 'medium',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Mixed crops / Livestock',
    pvuStatus: true,
    vadEnrolled: 'EVAD',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-003',
    owner: 'Williams, David',
    address: '4550 Alamance Church Rd, Liberty, NC',
    lat: 35.892, lon: -79.702,
    acreage: 12,
    soilType: 'Madison gravelly sandy loam (MdC)',
    soilDrainage: 'Well drained',
    slopePct: '8-15%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '> 1000ft',
    concerns: ['Severe sheet and rill erosion', 'Low organic matter'],
    practices: [
      {code: '600', name: 'Terrace', priority: 'high'},
      {code: '412', name: 'Grassed Waterway', priority: 'medium'}
    ],
    eqipEstimate: '$3,500 - $7,000',
    priorityScore: 92,
    priorityLevel: 'high',
    zoning: 'RS-40',
    zoningDesc: 'Residential Single-Family (40K sf lots)',
    landUse: 'Hay / Pasture',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: false,
    farmClass: 'potential-farm'
  },
  {
    id: 'parcel-004',
    owner: 'Brown, Michael',
    address: '3210 Yanceyville St, Greensboro, NC',
    lat: 35.941, lon: -79.821,
    acreage: 5,
    soilType: 'Urban Land - Cecil complex (UcC)',
    soilDrainage: 'Moderately well drained',
    slopePct: '2-10%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '800ft - North Buffalo Creek',
    concerns: ['High runoff curve', 'Limited pollinator habitat'],
    practices: [
      {code: '420', name: 'Wildlife Habitat Planting', priority: 'low'},
      {code: '612', name: 'Tree/Shrub Establishment', priority: 'medium'}
    ],
    eqipEstimate: '$1,000 - $2,500',
    priorityScore: 45,
    priorityLevel: 'low',
    zoning: 'R-A',
    zoningDesc: 'Residential Agricultural',
    landUse: 'Community garden / Urban agriculture',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-005',
    owner: 'Davis, Robert',
    address: '7600 NC Highway 150, Browns Summit, NC',
    lat: 36.235, lon: -79.632,
    acreage: 80,
    soilType: 'Pacolet sandy clay loam (PaD2)',
    soilDrainage: 'Well drained',
    slopePct: '10-15%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '250ft - Haw River Tributary',
    concerns: ['Gully erosion', 'Degraded pasture condition', 'Livestock stream access'],
    practices: [
      {code: '382', name: 'Fence', priority: 'high'},
      {code: '512', name: 'Pasture and Hay Planting', priority: 'high'},
      {code: '614', name: 'Watering Facility', priority: 'medium'}
    ],
    eqipEstimate: '$15,000 - $25,000',
    priorityScore: 95,
    priorityLevel: 'high',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Tobacco / Row crops',
    pvuStatus: true,
    vadEnrolled: 'VAD',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-006',
    owner: 'Miller, Jennifer',
    address: '5400 Bunch Rd, Summerfield, NC',
    lat: 36.275, lon: -79.785,
    acreage: 32,
    soilType: 'Cecil sandy loam (CeB2)',
    soilDrainage: 'Well drained',
    slopePct: '2-8%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '600ft',
    concerns: ['Monoculture cropping', 'Soil compaction'],
    practices: [
      {code: '340', name: 'Cover Crop', priority: 'medium'},
      {code: '328', name: 'Conservation Crop Rotation', priority: 'medium'}
    ],
    eqipEstimate: '$2,500 - $5,000',
    priorityScore: 65,
    priorityLevel: 'medium',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Hay / Pasture',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-007',
    owner: 'Wilson, Patricia',
    address: '2100 Pleasant Ridge Rd, Summerfield, NC',
    lat: 36.155, lon: -79.981,
    acreage: 18,
    soilType: 'Appling sandy loam (ApC)',
    soilDrainage: 'Well drained',
    slopePct: '6-10%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '400ft',
    concerns: ['Invasive species', 'Poor forest health'],
    practices: [
      {code: '314', name: 'Brush Management', priority: 'medium'},
      {code: '666', name: 'Forest Stand Improvement', priority: 'high'}
    ],
    eqipEstimate: '$3,000 - $6,500',
    priorityScore: 78,
    priorityLevel: 'high',
    zoning: 'RS-40',
    zoningDesc: 'Residential Single-Family (40K sf lots)',
    landUse: 'Horse farm / Pasture',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: false,
    farmClass: 'potential-farm'
  },
  {
    id: 'parcel-008',
    owner: 'Moore, Richard',
    address: '4300 Hicone Rd, Greensboro, NC',
    lat: 36.102, lon: -79.555,
    acreage: 65,
    soilType: 'Enon fine sandy loam (EnB)',
    soilDrainage: 'Well drained',
    slopePct: '2-6%',
    floodZone: 'Zone AE',
    wetlands: true,
    streamProximity: '50ft - Reedy Fork Creek',
    concerns: ['Riparian buffer degradation', 'Nutrient leaching'],
    practices: [
      {code: '391', name: 'Riparian Forest Buffer', priority: 'high'},
      {code: '590', name: 'Nutrient Management', priority: 'high'}
    ],
    eqipEstimate: '$12,000 - $18,000',
    priorityScore: 88,
    priorityLevel: 'high',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Cattle / Pasture',
    pvuStatus: true,
    vadEnrolled: 'EVAD',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-009',
    owner: 'Taylor, Linda',
    address: '1500 E Lee St, Greensboro, NC',
    lat: 35.915, lon: -79.881,
    acreage: 7,
    soilType: 'Urban Land (Ur)',
    soilDrainage: 'Variable',
    slopePct: '0-4%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '> 1000ft',
    concerns: ['Stormwater runoff', 'Lack of biodiversity'],
    practices: [
      {code: '430', name: 'Irrigation Pipeline', priority: 'low'},
      {code: '327', name: 'Conservation Cover', priority: 'medium'}
    ],
    eqipEstimate: '$1,500 - $3,000',
    priorityScore: 42,
    priorityLevel: 'low',
    zoning: 'CD',
    zoningDesc: 'Conditional District',
    landUse: 'Community garden / Urban farm',
    pvuStatus: false,
    vadEnrolled: 'none',
    bonaFideFarm: false,
    farmClass: 'non-agricultural'
  },
  {
    id: 'parcel-010',
    owner: 'Anderson, William',
    address: '6700 E Washington St, Julian, NC',
    lat: 35.873, lon: -79.595,
    acreage: 55,
    soilType: 'Georgeville silt loam (GeB)',
    soilDrainage: 'Well drained',
    slopePct: '2-6%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '300ft',
    concerns: ['Pesticide drift', 'Soil health decline'],
    practices: [
      {code: '595', name: 'Pest Management Conservation System', priority: 'medium'},
      {code: '340', name: 'Cover Crop', priority: 'medium'}
    ],
    eqipEstimate: '$5,000 - $9,000',
    priorityScore: 68,
    priorityLevel: 'medium',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Row crops / Vegetables',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-011',
    owner: 'Thomas, Charles',
    address: '8900 W Market St, Colfax, NC',
    lat: 36.011, lon: -79.962,
    acreage: 28,
    soilType: 'Cecil clay loam (CeC3)',
    soilDrainage: 'Well drained',
    slopePct: '6-10%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '500ft',
    concerns: ['Severe historical erosion', 'Low fertility'],
    practices: [
      {code: '328', name: 'Conservation Crop Rotation', priority: 'high'},
      {code: '412', name: 'Grassed Waterway', priority: 'medium'}
    ],
    eqipEstimate: '$4,000 - $7,500',
    priorityScore: 82,
    priorityLevel: 'high',
    zoning: 'RD',
    zoningDesc: 'Rural Density Residential',
    landUse: 'Mixed crops / Poultry',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: true,
    farmClass: 'likely-farm'
  },
  {
    id: 'parcel-012',
    owner: 'Jackson, Mary',
    address: '3400 N Church St, Greensboro, NC',
    lat: 36.254, lon: -79.862,
    acreage: 14,
    soilType: 'Madison gravelly sandy loam (MdD)',
    soilDrainage: 'Well drained',
    slopePct: '10-15%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '> 1000ft',
    concerns: ['Steep slopes', 'Water retention'],
    practices: [
      {code: '600', name: 'Terrace', priority: 'high'},
      {code: '612', name: 'Tree/Shrub Establishment', priority: 'low'}
    ],
    eqipEstimate: '$3,000 - $6,000',
    priorityScore: 75,
    priorityLevel: 'medium',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Goat farm / Pasture',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: false,
    farmClass: 'likely-farm'
  },
  {
    id: 'parcel-013',
    owner: 'White, John',
    address: '5600 High Point Rd, Greensboro, NC',
    lat: 35.923, lon: -79.751,
    acreage: 38,
    soilType: 'Appling sandy loam (ApB)',
    soilDrainage: 'Well drained',
    slopePct: '2-6%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '200ft',
    concerns: ['Irrigation inefficiency', 'Nutrient management'],
    practices: [
      {code: '449', name: 'Irrigation Water Management', priority: 'medium'},
      {code: '590', name: 'Nutrient Management', priority: 'medium'}
    ],
    eqipEstimate: '$6,000 - $11,000',
    priorityScore: 70,
    priorityLevel: 'medium',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Row crops / Hay',
    pvuStatus: true,
    vadEnrolled: 'VAD',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-014',
    owner: 'Harris, Barbara',
    address: '1200 S Elm-Eugene St, Greensboro, NC',
    lat: 35.862, lon: -79.811,
    acreage: 9,
    soilType: 'Urban Land - Enon complex (UrE)',
    soilDrainage: 'Moderately well drained',
    slopePct: '2-8%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '> 1000ft',
    concerns: ['Urban soil compaction', 'Lack of pollinators'],
    practices: [
      {code: '420', name: 'Wildlife Habitat Planting', priority: 'medium'},
      {code: '327', name: 'Conservation Cover', priority: 'low'}
    ],
    eqipEstimate: '$1,200 - $2,800',
    priorityScore: 50,
    priorityLevel: 'low',
    zoning: 'RS-40',
    zoningDesc: 'Residential Single-Family (40K sf lots)',
    landUse: 'Hobby farm / Vegetables',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: false,
    farmClass: 'potential-farm'
  },
  {
    id: 'parcel-015',
    owner: 'Martin, Daniel',
    address: '4500 Groomtown Rd, Greensboro, NC',
    lat: 35.972, lon: -79.935,
    acreage: 50,
    soilType: 'Pacolet sandy loam (PaC)',
    soilDrainage: 'Well drained',
    slopePct: '6-10%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '400ft',
    concerns: ['Pasture degradation', 'Livestock watering'],
    practices: [
      {code: '528', name: 'Prescribed Grazing', priority: 'high'},
      {code: '614', name: 'Watering Facility', priority: 'high'}
    ],
    eqipEstimate: '$9,000 - $16,000',
    priorityScore: 90,
    priorityLevel: 'high',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Pasture / Livestock grazing',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-016',
    owner: 'Thompson, Susan',
    address: '8900 US Highway 29 N, Browns Summit, NC',
    lat: 36.291, lon: -79.671,
    acreage: 22,
    soilType: 'Cecil sandy loam (CeB2)',
    soilDrainage: 'Well drained',
    slopePct: '4-8%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '300ft',
    concerns: ['Soil erosion', 'Weed pressure'],
    practices: [
      {code: '340', name: 'Cover Crop', priority: 'medium'},
      {code: '314', name: 'Brush Management', priority: 'low'}
    ],
    eqipEstimate: '$2,500 - $4,500',
    priorityScore: 62,
    priorityLevel: 'medium',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Cattle / Hay',
    pvuStatus: true,
    vadEnrolled: 'EVAD',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-017',
    owner: 'Garcia, Joseph',
    address: '3300 E Bessemer Ave, Greensboro, NC',
    lat: 36.152, lon: -79.531,
    acreage: 6,
    soilType: 'Mecklenburg loam (MeB)',
    soilDrainage: 'Well drained',
    slopePct: '2-6%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '800ft',
    concerns: ['Low organic matter', 'Water retention'],
    practices: [
      {code: '328', name: 'Conservation Crop Rotation', priority: 'medium'},
      {code: '449', name: 'Irrigation Water Management', priority: 'low'}
    ],
    eqipEstimate: '$1,500 - $3,500',
    priorityScore: 55,
    priorityLevel: 'low',
    zoning: 'R-3',
    zoningDesc: 'Residential Low-Density',
    landUse: 'Small vegetable farm',
    pvuStatus: false,
    vadEnrolled: 'none',
    bonaFideFarm: false,
    farmClass: 'non-agricultural'
  },
  {
    id: 'parcel-018',
    owner: 'Martinez, Margaret',
    address: '7700 W Wendover Ave, Jamestown, NC',
    lat: 35.951, lon: -79.951,
    acreage: 35,
    soilType: 'Appling sandy loam (ApC)',
    soilDrainage: 'Well drained',
    slopePct: '6-10%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '250ft',
    concerns: ['Riparian degradation', 'Soil erosion'],
    practices: [
      {code: '391', name: 'Riparian Forest Buffer', priority: 'high'},
      {code: '412', name: 'Grassed Waterway', priority: 'medium'}
    ],
    eqipEstimate: '$5,000 - $10,000',
    priorityScore: 85,
    priorityLevel: 'high',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Row crops / Tobacco',
    pvuStatus: true,
    vadEnrolled: 'VAD',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-019',
    owner: 'Robinson, Christopher',
    address: '1100 N Elm St, Greensboro, NC',
    lat: 36.245, lon: -79.741,
    acreage: 8,
    soilType: 'Urban Land - Cecil complex (UcC)',
    soilDrainage: 'Moderately well drained',
    slopePct: '2-10%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '> 1000ft',
    concerns: ['Urban soil compaction', 'Pollinator habitat'],
    practices: [
      {code: '420', name: 'Wildlife Habitat Planting', priority: 'medium'},
      {code: '612', name: 'Tree/Shrub Establishment', priority: 'low'}
    ],
    eqipEstimate: '$1,800 - $3,200',
    priorityScore: 48,
    priorityLevel: 'low',
    zoning: 'RD',
    zoningDesc: 'Rural Density Residential',
    landUse: 'Market garden / Herbs',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: false,
    farmClass: 'potential-farm'
  },
  {
    id: 'parcel-020',
    owner: 'Clark, Betty',
    address: '5500 N Church St, Greensboro, NC',
    lat: 36.182, lon: -79.561,
    acreage: 42,
    soilType: 'Cecil sandy loam (CeC2)',
    soilDrainage: 'Well drained',
    slopePct: '6-10%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '350ft',
    concerns: ['Erosion on steep slopes', 'Nutrient runoff'],
    practices: [
      {code: '600', name: 'Terrace', priority: 'high'},
      {code: '590', name: 'Nutrient Management', priority: 'medium'}
    ],
    eqipEstimate: '$8,000 - $14,000',
    priorityScore: 79,
    priorityLevel: 'high',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Swine / Row crops',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-021',
    owner: 'Rodriguez, Paul',
    address: '2200 S Holden Rd, Greensboro, NC',
    lat: 35.901, lon: -79.661,
    acreage: 15,
    soilType: 'Appling sandy loam (ApB)',
    soilDrainage: 'Well drained',
    slopePct: '2-6%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '500ft',
    concerns: ['Irrigation inefficiency', 'Soil health'],
    practices: [
      {code: '449', name: 'Irrigation Water Management', priority: 'medium'},
      {code: '340', name: 'Cover Crop', priority: 'medium'}
    ],
    eqipEstimate: '$3,500 - $6,500',
    priorityScore: 66,
    priorityLevel: 'medium',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Hay / Cattle',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: false,
    farmClass: 'likely-farm'
  },
  {
    id: 'parcel-022',
    owner: 'Lewis, Nancy',
    address: '9900 US Highway 421 S, Julian, NC',
    lat: 35.852, lon: -79.732,
    acreage: 60,
    soilType: 'Georgeville silt loam (GeB)',
    soilDrainage: 'Well drained',
    slopePct: '2-6%',
    floodZone: 'Zone AE',
    wetlands: true,
    streamProximity: '100ft',
    concerns: ['Flooding risk', 'Riparian buffer lacking'],
    practices: [
      {code: '391', name: 'Riparian Forest Buffer', priority: 'high'},
      {code: '327', name: 'Conservation Cover', priority: 'medium'}
    ],
    eqipEstimate: '$10,000 - $18,000',
    priorityScore: 86,
    priorityLevel: 'high',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Row crops / Vegetables',
    pvuStatus: true,
    vadEnrolled: 'VAD',
    bonaFideFarm: true,
    farmClass: 'confirmed-farm'
  },
  {
    id: 'parcel-023',
    owner: 'Lee, Mark',
    address: '4400 Randleman Rd, Greensboro, NC',
    lat: 36.311, lon: -79.721,
    acreage: 25,
    soilType: 'Cecil sandy loam (CeB2)',
    soilDrainage: 'Well drained',
    slopePct: '4-8%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '450ft',
    concerns: ['Soil compaction', 'Nutrient management'],
    practices: [
      {code: '328', name: 'Conservation Crop Rotation', priority: 'medium'},
      {code: '590', name: 'Nutrient Management', priority: 'medium'}
    ],
    eqipEstimate: '$4,000 - $8,000',
    priorityScore: 69,
    priorityLevel: 'medium',
    zoning: 'RS-40',
    zoningDesc: 'Residential Single-Family (40K sf lots)',
    landUse: 'Horse farm / Pasture',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: false,
    farmClass: 'potential-farm'
  },
  {
    id: 'parcel-024',
    owner: 'Walker, Karen',
    address: '3300 N Elm St, Greensboro, NC',
    lat: 36.061, lon: -79.501,
    acreage: 10,
    soilType: 'Madison gravelly sandy loam (MdC)',
    soilDrainage: 'Well drained',
    slopePct: '8-15%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '> 1000ft',
    concerns: ['Erosion risk', 'Low organic matter'],
    practices: [
      {code: '600', name: 'Terrace', priority: 'high'},
      {code: '340', name: 'Cover Crop', priority: 'medium'}
    ],
    eqipEstimate: '$2,500 - $5,500',
    priorityScore: 76,
    priorityLevel: 'high',
    zoning: 'AG',
    zoningDesc: 'Agricultural',
    landUse: 'Mixed crops / Livestock',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: false,
    farmClass: 'likely-farm'
  },
  {
    id: 'parcel-025',
    owner: 'Hall, Steven',
    address: '6600 Friendly Ave, Greensboro, NC',
    lat: 35.931, lon: -79.871,
    acreage: 12,
    soilType: 'Appling sandy loam (ApB)',
    soilDrainage: 'Well drained',
    slopePct: '2-6%',
    floodZone: 'Zone X (minimal)',
    wetlands: false,
    streamProximity: '600ft',
    concerns: ['Pollinator habitat', 'Water retention'],
    practices: [
      {code: '420', name: 'Wildlife Habitat Planting', priority: 'medium'},
      {code: '449', name: 'Irrigation Water Management', priority: 'low'}
    ],
    eqipEstimate: '$2,000 - $4,500',
    priorityScore: 58,
    priorityLevel: 'low',
    zoning: 'RD',
    zoningDesc: 'Rural Density Residential',
    landUse: 'Hobby farm / Orchard',
    pvuStatus: true,
    vadEnrolled: 'none',
    bonaFideFarm: false,
    farmClass: 'potential-farm'
  }
];
